# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        tags: |
          $(tag)

          - task: Docker@2
            inputs:
              containerRegistry: 'ApplicationACR'
              command: 'login'
              
              - task: aquasecScanner@4
                inputs:
                  image: '$(Build.Repository.Name):$(Build.BuildId)'
                  scanType: 'hosted'
                  register: true
                  hideBase: false
                  showNegligible: false
                  windowsScannerVersion: '4.2.0'
                  scanner: 'acemnldaquacr01.azurecr.io/aquasec/scanner:latest'
                  registry: 'xxxx.acr.io'
                  connection: 'Aquaconsoleconnection'
                  caCertificates: true

                  - task: Docker@2
                    inputs:
                      containerRegistry: 'ApplicationACR'
                      repository: 'qqqeqew'
                      command: 'push'